[package]
# Useful fields: name, version, authors, description, edition, license, repository
# For publishing: categories, documentation, homepage, exclude, keywords, readme

# Use #[cfg(docsrs)] for targeting, unstable features
# To document required features: #![cfg_attr(docsrs, feature(doc_cfg), feature(doc_auto_cfg), feature(doc_cfg_hide))],
# paired with #[cfg(any(doc, feature = "extra-feat"))]
# Also keep an eye on https://doc.rust-lang.org/nightly/rustdoc/scraped-examples.html for the future

[lints.clippy]
missing_docs_in_private_items = "warn"

[lints.rust]
missing_docs = "warn"